### ISSUE TITLE
Missing dependency Jest in search path

### ISSUE THREAD

**Issue by sunday-hadrien-menspellen** [glennsl/rescript-jest#104]
Hey !

I am new to Rescript and all the ecosystem. I tried installing and running rescript-jest but I get the following error: Missing dependency Jest in search path.

Could you point me in the right direction ?

The code is here: [https://gitlab.com/hadrienmp/mob-fr-diamond-kata/-/tree/rescript](https://gitlab.com/hadrienmp/mob-fr-diamond-kata/-/tree/rescript)

**Comment by glennsl** [comment]
Which command is producing that error?

**Comment by glennsl** [comment]
One potential problem I see is that you're not building with `-with-deps`. Unless `rescript` adds that for you automatically these days, this will not build your dependencies and hence will not have the `Jest` module available.

**Comment by sunday-hadrien-menspellen** [comment]
Perfect ! That was exactly it thank you so much. Sorry for the trivial question.
