### ISSUE TITLE
In-browser example

### ISSUE THREAD

**Issue by varnerac** [glennsl/rescript-jest#111]
This may be out of scope for your project, but I'm looking for an example using karma or a similar technique when I need to test against a specific browser API. No worries if this isn't something you're interested in.

**Comment by glennsl** [comment]
Hi. Sorry, I'm not sure Karma even integrates with Jest, or anything else that provides the same functionality. But if you can find an example of something that works with Jest in plain JavaScript, I could perhaps assist in translating that to rescript-jest.

**Comment by varnerac** [comment]
I'll play around with Mocha, but I think it's a bit out of scope here.
